"""Persistence and transaction contracts for authoritative use cases."""
from __future__ import annotations
from contextlib import AbstractContextManager
from dataclasses import dataclass
from datetime import datetime
from typing import Protocol
from uuid import UUID
from app.domain.contracts import Contract, ContractTemplate
from app.domain.primitives import Character, InventoryStack, Job, LedgerEntry, Vehicle, Wallet
from app.domain.settlements import Settlement
@dataclass(frozen=True,slots=True)
class IdempotencyRecord: command_name:str; idempotency_key:str; request_hash:str; response_status:int; response_payload:dict; actor_id:UUID|None; created_at:datetime
@dataclass(frozen=True,slots=True)
class OutboxEvent: id:UUID; event_type:str; aggregate_type:str; aggregate_id:UUID; payload:dict; attempts:int; lease_owner:str|None; lease_until:datetime|None
class WalletRepository(Protocol):
    def get(self,wallet_id:UUID)->Wallet|None: ...
    def save(self,wallet:Wallet)->None: ...
    def add_ledger_entry(self,entry:LedgerEntry)->None: ...
    def get_ledger_entry_by_idempotency_key(self,key:str)->LedgerEntry|None: ...
class InventoryRepository(Protocol):
    def get_stack(self,inventory_id:UUID,item_definition_id:UUID)->InventoryStack|None: ...
    def save_stack(self,inventory_id:UUID,stack:InventoryStack)->None: ...
    def delete_stack(self,inventory_id:UUID,item_definition_id:UUID,expected_version:int)->None: ...
class JobRepository(Protocol):
    def get(self,job_id:UUID)->Job|None: ...
    def get_by_idempotency_key(self,key:str)->Job|None: ...
    def save(self,job:Job)->None: ...
    def bind_idempotency_key(self,key:str,job_id:UUID)->None: ...
class CharacterRepository(Protocol):
    def get(self,character_id:UUID)->Character|None: ...
    def get_by_player_id(self,player_id:UUID)->Character|None: ...
    def save(self,character:Character)->None: ...
class VehicleRepository(Protocol):
    def get(self,vehicle_id:UUID)->Vehicle|None: ...
    def list_by_owner(self,owner_id:UUID)->list[Vehicle]: ...
    def lock_owner_for_starter(self,owner_id:UUID)->None: ...
    def save(self,vehicle:Vehicle)->None: ...
class SettlementRepository(Protocol):
    def get_by_owner(self,owner_id:UUID)->Settlement|None: ...
    def get(self,settlement_id:UUID)->Settlement|None: ...
    def save(self,settlement:Settlement)->None: ...
class ContractRepository(Protocol):
    def save_template(self,template:ContractTemplate)->None: ...
    def get_template(self,template_id:UUID)->ContractTemplate|None: ...
    def save(self,contract:Contract)->None: ...
    def get(self,contract_id:UUID)->Contract|None: ...
    def list_for_player(self,player_id:UUID)->list[Contract]: ...
    def has_completed_template(self,player_id:UUID,template_id:UUID)->bool: ...
    def get_reputation(self,player_id:UUID,faction_id:str)->int: ...
    def add_reputation(self,player_id:UUID,faction_id:str,amount:int)->None: ...
    def wallet_id(self,player_id:UUID)->UUID|None: ...
@dataclass(frozen=True,slots=True)
class InventoryStackSnapshot: inventory_id:UUID; item_definition_id:UUID; quantity:int; condition:int; version:int
@dataclass(frozen=True,slots=True)
class PlayerStateSnapshot: wallet:Wallet|None; inventory:list[InventoryStackSnapshot]; active_jobs:list[Job]
class PlayerStateRepository(Protocol):
    """Read model for the authoritative account snapshot used by Android reconnect/bootstrap."""
    def snapshot(self,player_id:UUID)->PlayerStateSnapshot: ...
class IdempotencyRepository(Protocol):
    def get(self,command_name:str,idempotency_key:str)->IdempotencyRecord|None: ...
    def put(self,record:IdempotencyRecord)->None: ...
class AuditRepository(Protocol):
    def append(self,event_type:str,aggregate_type:str,aggregate_id:UUID,payload:dict)->None: ...
class OutboxRepository(Protocol):
    def enqueue(self,event_type:str,aggregate_type:str,aggregate_id:UUID,payload:dict)->None: ...
    def claim(self,owner:str,limit:int=50,lease_seconds:int=60,max_attempts:int=10)->list[OutboxEvent]: ...
    def mark_published(self,event_id:UUID,owner:str)->None: ...
    def mark_failed(self,event_id:UUID,owner:str,error:str,retry_after_seconds:int)->None: ...
class UnitOfWork(AbstractContextManager["UnitOfWork"],Protocol):
    wallets:WalletRepository; inventories:InventoryRepository; jobs:JobRepository; characters:CharacterRepository; vehicles:VehicleRepository; settlements:SettlementRepository; contracts:ContractRepository; player_state:PlayerStateRepository; idempotency:IdempotencyRepository; audit:AuditRepository; outbox:OutboxRepository
    def commit(self)->None: ...
    def rollback(self)->None: ...
    def __enter__(self)->"UnitOfWork": ...
    def __exit__(self,exc_type,exc_value,traceback)->None: ...
