package com.jotalbot.madworld

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.jotalbot.madworld.data.NotificationCenter

private enum class GameScreen(val title:String,val icon:String){HOME("Base","⌂"),WORLD("World","◉"),FLEET("Fleet","◆"),ECONOMY("Market","₿"),SOCIAL("Crew","♟"),TERRITORY("Territory","▣")}

class GameActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{B7GameShell()}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun B7GameShell(vm:PlayerViewModel=viewModel()){
 val context=LocalContext.current
 val state by vm.uiState.collectAsStateWithLifecycle();var screen by remember{mutableStateOf(GameScreen.HOME)};var handle by remember{mutableStateOf("Wanderer")};var character by remember{mutableStateOf("Wanderer")};val notifications=remember(context){NotificationCenter(context)};val notices by notifications.items.collectAsStateWithLifecycle();LaunchedEffect(Unit){vm.load()}
 MaterialTheme{Surface(Modifier.fillMaxSize()){when(val s=state){PlayerUiState.Loading->Box(Modifier.fillMaxSize(),contentAlignment=androidx.compose.ui.Alignment.Center){CircularProgressIndicator(Modifier.semantics{contentDescription="Loading MadWorld"})};PlayerUiState.SignedOut->Column(Modifier.padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("MadWorld",style=MaterialTheme.typography.headlineLarge);Text("Enter the persistent wasteland");OutlinedTextField(handle,{handle=it},label={Text("Handle")},singleLine=true,modifier=Modifier.fillMaxWidth());Button({vm.signIn(handle)},Modifier.fillMaxWidth().semantics{contentDescription="Connect to MadWorld"}){Text("Connect")}};is PlayerUiState.Error->Column(Modifier.padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Connection problem",style=MaterialTheme.typography.headlineSmall);Text(s.message);Button({vm.load()},modifier=Modifier.semantics{contentDescription="Retry connection"}){Text("Retry")}};is PlayerUiState.Ready->Column(Modifier.fillMaxSize()){TopAppBar(title={Text("${screen.title} · MadWorld")},actions={if(s.offline)Text("OFFLINE",modifier=Modifier.padding(end=12.dp).semantics{contentDescription="Offline mode"},color=MaterialTheme.colorScheme.error);if(notices.any{!it.read})Text("● ${notices.count{!it.read}}",modifier=Modifier.padding(end=12.dp).semantics{contentDescription="Unread notifications"})});Column(Modifier.weight(1f).verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){if(s.state.character==null){Text("Create your pilot",style=MaterialTheme.typography.headlineSmall);OutlinedTextField(character,{character=it},label={Text("Character")},singleLine=true,modifier=Modifier.fillMaxWidth());Button({vm.bootstrap(character)},enabled=character.isNotBlank(),modifier=Modifier.semantics{contentDescription="Enter the wasteland"}){Text("Enter the wasteland")}}else{if(notices.any{!it.read})Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Notifications",style=MaterialTheme.typography.titleLarge);notices.filter{!it.read}.take(3).forEach{n->Text(n.title,style=MaterialTheme.typography.titleMedium);Text(n.body);TextButton({notifications.markRead(n.id)},modifier=Modifier.semantics{contentDescription="Mark ${n.title} as read"}){Text("Read")}}};};when(screen){GameScreen.HOME->HomeScreen(s);GameScreen.WORLD->WorldScreen(s,vm);GameScreen.FLEET->FleetScreen(s);GameScreen.ECONOMY->EconomyScreen(s,vm);GameScreen.SOCIAL->SocialScreen(s,vm);GameScreen.TERRITORY->TerritoryScreen(s,vm)}}};NavigationBar{GameScreen.values().forEach{item->NavigationBarItem(selected=screen==item,onClick={screen=item},icon={Text(item.icon)},label={Text(item.title)},modifier=Modifier.semantics{contentDescription="Open ${item.title}"})}}}}}}
}
@Composable private fun HomeScreen(s:PlayerUiState.Ready){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Pilot",style=MaterialTheme.typography.titleLarge);Text(s.session.handle);s.state.character?.let{Text("${it.name} · level ${it.level}")};s.state.vehicles.firstOrNull()?.let{Text("Vehicle · ${it.chassisCode} · fuel ${it.fuel} · durability ${it.durability}")};Text(if(s.offline)"Cached state. Authoritative commands wait for connectivity." else "Server-authoritative state synchronized.")}};s.settlement?.let{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("Settlement",style=MaterialTheme.typography.titleLarge);Text("${it.region} · level ${it.level}")}}}}
@Composable private fun WorldScreen(s:PlayerUiState.Ready,vm:PlayerViewModel){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Dynamic World",style=MaterialTheme.typography.titleLarge);val w=s.world;if(w==null)Text(s.worldError?:"World unavailable")else{Text("Season ${w.season} · tick ${w.tick}");Text("Factions ${w.factions.size} · events ${w.events.size} · missions ${w.missions.size}");w.pressures.take(5).forEach{Text("${it.regionId} · ${it.resourceType} · ${it.pressureBps} bps")}};OutlinedButton({vm.refreshWorld()},modifier=Modifier.semantics{contentDescription="Refresh world state"}){Text("Refresh")}}}}
@Composable private fun FleetScreen(s:PlayerUiState.Ready){Text("Fleet",style=MaterialTheme.typography.headlineSmall);s.state.vehicles.forEach{v->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text(v.chassisCode,style=MaterialTheme.typography.titleLarge);Text("Fuel ${v.fuel} · durability ${v.durability} · ${v.state}")}}}}
@Composable private fun EconomyScreen(s:PlayerUiState.Ready,vm:PlayerViewModel){val e=s.economy;Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Regional Economy",style=MaterialTheme.typography.titleLarge);if(e==null)Text(s.economyError?:"Economy unavailable")else{Text("Region ${e.region}");Text("Warehouse ${e.warehouseUsed}/${e.warehouseCapacity}");Text("Production ${e.activeJobs.size}");Text("Contracts ${e.contractCount}")};OutlinedButton({vm.refreshEconomy()},modifier=Modifier.semantics{contentDescription="Refresh economy"}){Text("Refresh")}}}}
@Composable private fun SocialScreen(s:PlayerUiState.Ready,vm:PlayerViewModel){val c=s.corporation;Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Crew & Corporation",style=MaterialTheme.typography.titleLarge);if(c==null)Text(s.socialError?:"No corporation loaded")else{Text("${c.name} [${c.code}]");Text("Role ${c.role} · members ${c.memberCount}");Text("Wallet ${s.socialWalletBalance?:0}");OutlinedButton({vm.refreshCorporation(c.id)},modifier=Modifier.semantics{contentDescription="Refresh crew"}){Text("Refresh crew")};OutlinedButton({vm.refreshCorporateWallet(c.id)},modifier=Modifier.semantics{contentDescription="Refresh corporate wallet"}){Text("Refresh wallet")}}}}}
@Composable private fun TerritoryScreen(s:PlayerUiState.Ready,vm:PlayerViewModel){val t=s.territory;Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Territory",style=MaterialTheme.typography.titleLarge);if(t==null)Text(s.territoryError?:"Territory unavailable")else{Text("Regions ${t.regions.size} · roads ${t.roads.size}");Text("Resource sites ${t.resourceSites.size}");t.regions.forEach{Text("${it.name} · ${it.security}")}};OutlinedButton({vm.refreshTerritory()},modifier=Modifier.semantics{contentDescription="Refresh territory"}){Text("Refresh")}}}}