package com.jotalbot.madworld

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel

class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{MadWorldApp()}}}
@Composable private fun MadWorldApp(viewModel:PlayerViewModel=viewModel()){
 val uiState by viewModel.uiState.collectAsStateWithLifecycle();var handle by remember{mutableStateOf("Wanderer")};var characterName by remember{mutableStateOf("Wanderer")};var corpCode by remember{mutableStateOf("")};var corpName by remember{mutableStateOf("")};var brandName by remember{mutableStateOf("")};var quality by remember{mutableStateOf("5000")};LaunchedEffect(Unit){viewModel.load()}
 MaterialTheme{Surface(Modifier.fillMaxSize()){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(12.dp)){Text("MadWorld",style=MaterialTheme.typography.headlineLarge);Text("Persistent wasteland online");when(val state=uiState){PlayerUiState.Loading->CircularProgressIndicator(Modifier.padding(24.dp));PlayerUiState.SignedOut->{OutlinedTextField(handle,{handle=it},label={Text("Handle")},singleLine=true,modifier=Modifier.fillMaxWidth());Button({viewModel.signIn(handle)},Modifier.fillMaxWidth()){Text("Connect")}};is PlayerUiState.Ready->{Text("Pilot: ${state.session.handle}",style=MaterialTheme.typography.titleLarge);state.state.character?.let{Text("${it.name} · level ${it.level}")};state.state.vehicles.firstOrNull()?.let{Text("Vehicle: ${it.chassisCode} · fuel ${it.fuel} · durability ${it.durability}")};if(state.state.character==null){OutlinedTextField(characterName,{characterName=it},label={Text("Character")},singleLine=true,modifier=Modifier.fillMaxWidth());Button({viewModel.bootstrap(characterName)},Modifier.fillMaxWidth()){Text("Enter the wasteland")}};SettlementPanel(state,viewModel::refreshSettlement);EconomyPanel(state,viewModel::refreshEconomy);TerritoryPanel(state,viewModel::refreshTerritory);SocialPanel(state,corpCode,{corpCode=it},corpName,{corpName=it},brandName,{brandName=it},quality,{quality=it},viewModel::createCorporation,viewModel::refreshCorporation,viewModel::refreshCorporateWallet,viewModel::createManufacturer);if(state.offline)Text("Cached state",color=MaterialTheme.colorScheme.secondary)};is PlayerUiState.Error->{Text(state.message,color=MaterialTheme.colorScheme.error);Button({viewModel.load()}){Text("Retry")}}}}}}
}
@Composable private fun TerritoryPanel(state:PlayerUiState.Ready,onRefresh:()->Unit){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Territory",style=MaterialTheme.typography.titleLarge);val t=state.territory;if(t==null)Text(state.territoryError?:"Loading territory…",color=MaterialTheme.colorScheme.error)else{Text("Regions: ${t.regions.size} · controlled objects: ${t.control.count{it.controllerCorporationId!=null}}");Text("Roads: ${t.roads.size} · resource sites: ${t.resourceSites.size}");t.regions.forEach{r->Text("${r.name} · ${r.security}")};t.resourceSites.take(3).forEach{r->Text("Resource: ${r.name} ${r.remaining}/${r.capacity}")}};OutlinedButton(onRefresh,Modifier.fillMaxWidth()){Text("Refresh territory")}}}}
@Composable private fun SocialPanel(state:PlayerUiState.Ready,code:String,onCode:(String)->Unit,name:String,onName:(String)->Unit,brand:String,onBrand:(String)->Unit,quality:String,onQuality:(String)->Unit,onCreate:(String,String,Int)->Unit,onRefreshCorp:(java.util.UUID)->Unit,onRefreshWallet:(java.util.UUID)->Unit,onCreateManufacturer:(String,Int)->Unit){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Social Sandbox",style=MaterialTheme.typography.titleLarge);val corp=state.corporation;if(corp!=null){Text("${corp.name} [${corp.code}]");Text("Role: ${corp.role} · members: ${corp.memberCount}");Text("Corporate tax: ${corp.taxBps/100.0}%");Text("Corporate wallet: ${state.socialWalletBalance?.toString()?:"unavailable"}");OutlinedButton({onRefreshCorp(corp.id)},Modifier.fillMaxWidth()){Text("Refresh corporation")};OutlinedButton({onRefreshWallet(corp.id)},Modifier.fillMaxWidth()){Text("Refresh wallet")};HorizontalDivider();Text("Manufacturer / brand",style=MaterialTheme.typography.titleMedium);OutlinedTextField(brand,onBrand,label={Text("Brand")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(quality,onQuality,label={Text("Quality 0..10000")},singleLine=true,modifier=Modifier.fillMaxWidth());Button({onCreateManufacturer(brand,quality.toIntOrNull()?:5000)},enabled=brand.length>=2&&(quality.toIntOrNull()?:-1) in 0..10000,modifier=Modifier.fillMaxWidth()){Text("Create manufacturer")};state.socialError?.let{Text(it,color=MaterialTheme.colorScheme.error)}}else{Text(state.socialError?:"No corporation loaded");OutlinedTextField(code,onCode,label={Text("Code")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(name,onName,label={Text("Name")},singleLine=true,modifier=Modifier.fillMaxWidth());Button({onCreate(code,name,0)},enabled=code.length>=2&&name.length>=2,modifier=Modifier.fillMaxWidth()){Text("Create corporation")}}}}
}
@Composable private fun SettlementPanel(state:PlayerUiState.Ready,onRefresh:()->Unit){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Settlement",style=MaterialTheme.typography.titleLarge);val s=state.settlement;if(s==null)Text(state.settlementError?:"Loading settlement…",color=MaterialTheme.colorScheme.error)else{Text("Region: ${s.region}");Text("Level: ${s.level} · version ${s.version}");Text("Modules: ${s.modules.size}")};OutlinedButton(onRefresh,Modifier.fillMaxWidth()){Text("Refresh settlement")}}}}
@Composable private fun EconomyPanel(state:PlayerUiState.Ready,onRefresh:()->Unit){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Economy loop",style=MaterialTheme.typography.titleLarge);val e=state.economy;if(e==null)Text(state.economyError?:"Loading economy…",color=MaterialTheme.colorScheme.error)else{Text("Region: ${e.region}");Text("Warehouse: ${e.warehouseUsed}/${e.warehouseCapacity}");Text("Active production: ${e.activeJobs.size}");Text("Available contracts: ${e.contractCount}");Text("Ready vehicles: ${e.readyVehicles}")};OutlinedButton(onRefresh,Modifier.fillMaxWidth()){Text("Refresh economy")}}}}
