package com.jotalbot.madworld
import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.jotalbot.madworld.data.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
sealed interface PlayerUiState {
    data object Loading:PlayerUiState; data object SignedOut:PlayerUiState
    data class Ready(val state:PlayerState,val session:SessionState,val settlement:SettlementState?=null,val economy:EconomyOverviewState?=null,val corporation:CorporationState?=null,val socialWalletBalance:Long?=null,val territory:TerritoryState?=null,val world:WorldState?=null,val offline:Boolean=false,val settlementError:String?=null,val economyError:String?=null,val socialError:String?=null,val territoryError:String?=null,val worldError:String?=null):PlayerUiState
    data class Error(val message:String,val cached:PlayerState?=null):PlayerUiState
}
class PlayerViewModel(application:Application):AndroidViewModel(application){
 private val repository=PlayerRepository(application,MadWorldApi(BuildConfig.MADWORLD_API_URL));private val worldRepository=WorldRepository(BuildConfig.MADWORLD_API_URL);private val _uiState=MutableStateFlow<PlayerUiState>(PlayerUiState.Loading);val uiState:StateFlow<PlayerUiState> = _uiState.asStateFlow()
 fun load(){val s=repository.session();if(s==null){_uiState.value=PlayerUiState.SignedOut;return};val cached=repository.cached(s.playerId);val cs=repository.cachedSettlement(s.playerId);if(cached!=null)_uiState.value=PlayerUiState.Ready(cached,s,cs,offline=true);viewModelScope.launch(Dispatchers.IO){runCatching{repository.refresh(s)}.onSuccess{state->val settlement=runCatching{repository.refreshSettlement(s)}.getOrNull()?:cs;val economy=runCatching{repository.refreshEconomy(s)}.getOrNull();val territory=runCatching{MadWorldApi(BuildConfig.MADWORLD_API_URL).fetchTerritory(s.token)}.getOrNull();val world=runCatching{worldRepository.fetch(s.token)}.getOrNull();_uiState.value=PlayerUiState.Ready(state,s,settlement,economy,territory=territory,world=world,offline=false,settlementError=if(settlement==null)"Settlement unavailable"else null,economyError=if(economy==null)"Economy unavailable"else null,territoryError=if(territory==null)"Territory unavailable"else null,worldError=if(world==null)"World unavailable"else null)}.onFailure{if(cached==null)_uiState.value=PlayerUiState.Error(it.message?:"Unable to load player state")}}}
 fun refreshSettlement(){val x=_uiState.value;if(x !is PlayerUiState.Ready)return;viewModelScope.launch(Dispatchers.IO){runCatching{repository.refreshSettlement(x.session)}.onSuccess{_uiState.value=x.copy(settlement=it,settlementError=null,offline=false)}.onFailure{_uiState.value=x.copy(settlementError=it.message?:"Unable to load settlement")}}}
 fun refreshEconomy(){val x=_uiState.value;if(x !is PlayerUiState.Ready)return;viewModelScope.launch(Dispatchers.IO){runCatching{repository.refreshEconomy(x.session)}.onSuccess{_uiState.value=x.copy(economy=it,economyError=null,offline=false)}.onFailure{_uiState.value=x.copy(economyError=it.message?:"Unable to load economy")}}}
 fun refreshTerritory(){val x=_uiState.value;if(x !is PlayerUiState.Ready)return;viewModelScope.launch(Dispatchers.IO){runCatching{MadWorldApi(BuildConfig.MADWORLD_API_URL).fetchTerritory(x.session.token)}.onSuccess{_uiState.value=x.copy(territory=it,territoryError=null,offline=false)}.onFailure{_uiState.value=x.copy(territoryError=it.message?:"Unable to load territory")}}}
 fun refreshWorld(){val x=_uiState.value;if(x !is PlayerUiState.Ready)return;viewModelScope.launch(Dispatchers.IO){runCatching{worldRepository.fetch(x.session.token)}.onSuccess{_uiState.value=x.copy(world=it,worldError=null,offline=false)}.onFailure{_uiState.value=x.copy(worldError=it.message?:"Unable to load world")}}}
 fun refreshCorporation(corporationId:java.util.UUID){val x=_uiState.value;if(x !is PlayerUiState.Ready)return;viewModelScope.launch(Dispatchers.IO){runCatching{MadWorldApi(BuildConfig.MADWORLD_API_URL).fetchCorporationOverview(corporationId,x.session.token)}.onSuccess{_uiState.value=x.copy(corporation=it,socialError=null)}.onFailure{_uiState.value=x.copy(socialError=it.message?:"Unable to load corporation")}}}
 fun refreshCorporateWallet(corporationId:java.util.UUID){val x=_uiState.value;if(x !is PlayerUiState.Ready)return;viewModelScope.launch(Dispatchers.IO){runCatching{MadWorldApi(BuildConfig.MADWORLD_API_URL).fetchCorporateWallet(corporationId,x.session.token)}.onSuccess{_uiState.value=x.copy(socialWalletBalance=it,socialError=null)}.onFailure{_uiState.value=x.copy(socialError=it.message?:"Unable to load corporate wallet")}}}
 fun createCorporation(code:String,name:String,taxBps:Int){val x=_uiState.value;if(x !is PlayerUiState.Ready)return;viewModelScope.launch(Dispatchers.IO){runCatching{MadWorldApi(BuildConfig.MADWORLD_API_URL).createCorporation(code.trim(),name.trim(),taxBps,x.session.token)}.onSuccess{refreshCorporation(it);refreshCorporateWallet(it)}.onFailure{_uiState.value=x.copy(socialError=it.message?:"Unable to create corporation")}}}
 fun createManufacturer(brand:String,quality:Int){val x=_uiState.value;if(x !is PlayerUiState.Ready||x.corporation==null)return;viewModelScope.launch(Dispatchers.IO){runCatching{MadWorldApi(BuildConfig.MADWORLD_API_URL).createManufacturer(x.corporation.id,brand.trim(),quality,x.session.token)}.onSuccess{_uiState.value=x.copy(socialError="Manufacturer created")} .onFailure{_uiState.value=x.copy(socialError=it.message?:"Unable to create manufacturer")}}}
 fun signIn(handle:String){_uiState.value=PlayerUiState.Loading;viewModelScope.launch(Dispatchers.IO){runCatching{repository.createSession(handle.trim())}.onSuccess{s->runCatching{repository.refresh(s)}.onSuccess{p->val settlement=runCatching{repository.refreshSettlement(s)}.getOrNull();val economy=runCatching{repository.refreshEconomy(s)}.getOrNull();val territory=runCatching{MadWorldApi(BuildConfig.MADWORLD_API_URL).fetchTerritory(s.token)}.getOrNull();val world=runCatching{worldRepository.fetch(s.token)}.getOrNull();_uiState.value=PlayerUiState.Ready(p,s,settlement,economy,territory=territory,world=world,settlementError=if(settlement==null)"Settlement unavailable"else null,economyError=if(economy==null)"Economy unavailable"else null,territoryError=if(territory==null)"Territory unavailable"else null,worldError=if(world==null)"World unavailable"else null)}.onFailure{_uiState.value=PlayerUiState.Error(it.message?:"Unable to load player state")}}.onFailure{_uiState.value=PlayerUiState.Error(it.message?:"Unable to create session")}}}
 fun bootstrap(characterName:String){val x=_uiState.value;if(x !is PlayerUiState.Ready)return;_uiState.value=PlayerUiState.Loading;viewModelScope.launch(Dispatchers.IO){runCatching{repository.bootstrap(x.session,characterName)}.onSuccess{p->_uiState.value=PlayerUiState.Ready(p,x.session,runCatching{repository.refreshSettlement(x.session)}.getOrNull()?:x.settlement,runCatching{repository.refreshEconomy(x.session)}.getOrNull()?:x.economy,territory=runCatching{MadWorldApi(BuildConfig.MADWORLD_API_URL).fetchTerritory(x.session.token)}.getOrNull()?:x.territory,world=runCatching{worldRepository.fetch(x.session.token)}.getOrNull()?:x.world)}.onFailure{_uiState.value=PlayerUiState.Error(it.message?:"Unable to bootstrap player")}}}
}