-- B3 Advanced Economy foundation.
-- market_price_history is owned by migration 012 and is intentionally not redefined here.
ALTER TABLE item_definitions ADD COLUMN IF NOT EXISTS mass_units INTEGER NOT NULL DEFAULT 1 CHECK (mass_units > 0);
CREATE TABLE IF NOT EXISTS regional_economic_state (region_id UUID PRIMARY KEY REFERENCES regions(id) ON DELETE CASCADE, supply_pressure_bps INTEGER NOT NULL DEFAULT 0 CHECK (supply_pressure_bps BETWEEN -10000 AND 10000), demand_pressure_bps INTEGER NOT NULL DEFAULT 0 CHECK (demand_pressure_bps BETWEEN -10000 AND 10000), liquidity_bps INTEGER NOT NULL DEFAULT 10000 CHECK (liquidity_bps BETWEEN 0 AND 100000), volatility_bps INTEGER NOT NULL DEFAULT 0 CHECK (volatility_bps BETWEEN 0 AND 10000), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0));
CREATE TABLE IF NOT EXISTS production_facilities (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID NOT NULL REFERENCES players(id), region_id UUID NOT NULL REFERENCES regions(id), name TEXT NOT NULL, facility_type TEXT NOT NULL, capacity_units INTEGER NOT NULL CHECK (capacity_units > 0), efficiency_bps INTEGER NOT NULL DEFAULT 10000 CHECK (efficiency_bps BETWEEN 1000 AND 20000), maintenance_bps INTEGER NOT NULL DEFAULT 0 CHECK (maintenance_bps BETWEEN 0 AND 10000), version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_production_facilities_owner_region ON production_facilities(owner_id, region_id);
CREATE TABLE IF NOT EXISTS production_recipes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, duration_seconds INTEGER NOT NULL CHECK (duration_seconds > 0), facility_type TEXT NOT NULL, inputs JSONB NOT NULL, outputs JSONB NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS production_jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID NOT NULL REFERENCES players(id), facility_id UUID NOT NULL REFERENCES production_facilities(id), recipe_id UUID NOT NULL REFERENCES production_recipes(id), batch_units INTEGER NOT NULL CHECK (batch_units > 0), state TEXT NOT NULL DEFAULT 'queued' CHECK (state IN ('queued','completed','cancelled')), started_at TIMESTAMPTZ NOT NULL, completes_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ, idempotency_key TEXT NOT NULL UNIQUE, version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0));
CREATE INDEX IF NOT EXISTS idx_production_jobs_owner_state ON production_jobs(owner_id, state, completes_at);
CREATE TABLE IF NOT EXISTS warehouses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID NOT NULL REFERENCES players(id), region_id UUID NOT NULL REFERENCES regions(id), name TEXT NOT NULL, capacity_units BIGINT NOT NULL CHECK (capacity_units > 0), used_units BIGINT NOT NULL DEFAULT 0 CHECK (used_units >= 0), version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK (used_units <= capacity_units));
CREATE INDEX IF NOT EXISTS idx_warehouses_owner_region ON warehouses(owner_id, region_id);
CREATE TABLE IF NOT EXISTS warehouse_items (warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE, item_definition_id UUID NOT NULL REFERENCES item_definitions(id), quantity BIGINT NOT NULL CHECK (quantity > 0), condition INTEGER NOT NULL DEFAULT 100 CHECK (condition BETWEEN 0 AND 100), PRIMARY KEY (warehouse_id, item_definition_id));
CREATE TABLE IF NOT EXISTS logistics_contracts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID NOT NULL REFERENCES players(id), source_warehouse_id UUID NOT NULL REFERENCES warehouses(id), destination_warehouse_id UUID NOT NULL REFERENCES warehouses(id), item_definition_id UUID NOT NULL REFERENCES item_definitions(id), quantity BIGINT NOT NULL CHECK (quantity > 0), reward BIGINT NOT NULL CHECK (reward >= 0), route_risk_bps INTEGER NOT NULL DEFAULT 0 CHECK (route_risk_bps BETWEEN 0 AND 10000), state TEXT NOT NULL DEFAULT 'accepted' CHECK (state IN ('accepted','in_transit','delivered','lost','cancelled')), idempotency_key TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), delivered_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0));
CREATE INDEX IF NOT EXISTS idx_logistics_owner_state ON logistics_contracts(owner_id, state, created_at);
CREATE TABLE IF NOT EXISTS player_economic_skills (player_id UUID PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE, production_level INTEGER NOT NULL DEFAULT 0 CHECK (production_level BETWEEN 0 AND 100), logistics_level INTEGER NOT NULL DEFAULT 0 CHECK (logistics_level BETWEEN 0 AND 100), trading_level INTEGER NOT NULL DEFAULT 0 CHECK (trading_level BETWEEN 0 AND 100), version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0));
INSERT INTO regional_economic_state(region_id) SELECT id FROM regions ON CONFLICT (region_id) DO NOTHING;
INSERT INTO production_recipes(code,name,duration_seconds,facility_type,inputs,outputs) VALUES ('refine_scrap_plate','Refine Scrap into Plate',60,'refinery','[{"item_code":"scrap_metal","quantity":5}]','[{"item_code":"metal_plate","quantity":1}]'),('refine_wire_bundle','Bundle Salvaged Wire',45,'assembly','[{"item_code":"salvaged_wire","quantity":4}]','[{"item_code":"wire_bundle","quantity":1}]') ON CONFLICT (code) DO NOTHING;
